version = 0.1

[default.deploy.parameters]
stack_name = "true-profit-mvp"
resolve_s3 = true
s3_prefix = "true-profit-mvp"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
